modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MairwunNx/COVID-19-Mod/issues"

[[mods]]
    modId="covid19"
    version="${file.jarVersion}"
    displayName="COVID-19"
    displayURL="https://github.com/MairwunNx/COVID-19-Mod"
    logoFile="covidwtf.png" # todo: create image before releasing.
    credits="Thanks to china for good idea for mod."
    authors="Pavel Erokhin, The bat"
    description='''
    This is a long story ... Just go into the world and play. Coronavirus in minecraft!
    '''

[[dependencies.covid19]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.covid19]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
